name: native_sqlite_example
description: Example usage of native_sqlite with code generation
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  native_sqlite:
    path: ../native_sqlite
  native_sqlite_annotation:
    path: ../native_sqlite_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  native_sqlite_generator:
    path: ../native_sqlite_generator
  flutter_lints: ^5.0.0
