name: native_sqlite_web
description: "Web implementation of native_sqlite using sqlite3 WASM"
version: 0.0.1
homepage: https://nesmin.dev
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

flutter:
  plugin:
    implements: native_sqlite
    platforms:
      web:
        pluginClass: NativeSqliteWeb
        fileName: native_sqlite_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  native_sqlite_platform_interface:
    git:
      url: https://github.com/dev-nesmin/native_sqllite.git
      path: native_sqlite_platform_interface
  sqlite3: ^2.4.6
  sqlite3_web: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
