name: native_sqlite_web
description: "Web implementation of native_sqlite using sqlite3 WASM"
version: 0.0.1
homepage: https://nesmin.dev
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

flutter:
  plugin:
    implements: native_sqlite
    platforms:
      web:
        pluginClass: NativeSqliteWeb
        fileName: native_sqlite_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  sqlite3: ^2.9.3
  sqlite3_web: ^0.3.2
  native_sqlite_platform_interface:
    path: ../native_sqlite_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
