name: native_sqlite_generator
description: "Code generator for native_sqlite - Generates table schemas and repositories from annotated classes"
version: 0.0.1
homepage: https://nesmin.dev
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  build: ^4.0.2
  source_gen: ^4.0.2
  analyzer: ^8.4.0
  yaml: ^3.1.2
  glob: ^2.1.2
  path: ^1.9.0
  native_sqlite_annotation:
    git:
      url: https://github.com/dev-nesmin/native_sqllite.git
      path: native_sqlite_annotation

dev_dependencies:
  lints: ^5.0.0
  build_runner: ^2.10.1
  build_test: ^3.5.1
