name: native_sqlite_generator
description: "Code generator for native_sqlite - Generates table schemas and repositories from annotated classes"
version: 0.0.1
homepage: https://nesmin.dev
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.9.0
  yaml: ^3.1.2
  glob: ^2.1.2
  path: ^1.9.0
  native_sqlite_annotation:
    path: ../native_sqlite_annotation

dev_dependencies:
  lints: ^5.0.0
  build_runner: ^2.4.13
  build_test: ^2.2.2
